apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  backoffLimit: 20
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: cassandra:4.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -ec
            - |
              until cqlsh cassandra 9042 -e "DESCRIBE KEYSPACES" >/dev/null 2>&1; do
                echo "waiting for cassandra..."
                sleep 5
              done

              cqlsh cassandra 9042 -f /schema/db.cql
          volumeMounts:
            - name: schema
              mountPath: /schema
      volumes:
        - name: schema
          configMap:
            name: cassandra-schema
